version: "3.8"

services:
  pingme_remote:
#    image: stream2stream/pingme
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: pmr
    restart: always
    ports:
      - "8097:8080"
  pingme_local:
      depends_on:
        - "pingme_remote"
      image: stream2stream/pingme
#      build:
#        context: .
#        dockerfile: ./dockerfile
      container_name: pmf
      restart: always
      ports:
        - "8095:8080"
      environment:
        PINGME_ENDPOINT: "pmr:8080"

networks:
  default:
    name: pingme-net
    external: false


